### ISSUE TITLE
Help please - Parse error in Cm_OrderProducts in Magento 1.9.2.2

### ISSUE THREAD

**Issue by webscot** [colinmollenhour/Cm_OrderProducts#3]
Attempted to use Cm_OrderProducts in Magento 1.9.2.2.

I received an error stating, "Parse error: syntax error, unexpected '[', expecting ')' in /public_html/app/code/community/Cm/OrderProducts/Block/Adminhtml/Sales/Order/Grid.php on line 63."

Line 63
['soi' => 'sales/order_item'],

Can you please suggest a solution?
Attempted to use Cm_OrderProducts in Magento 1.9.2.2.

I received an error stating, "Parse error: syntax error, unexpected '[', expecting ')' in /public_html/app/code/community/Cm/OrderProducts/Block/Adminhtml/Sales/Order/Grid.php on line 63."

Line 63
['soi' => 'sales/order_item'],

Can you please suggest a solution?

**Comment by colinmollenhour** [comment]
Looks like you are using PHP <5.3 and also not the latest master branch. PHP <5.3 is not supported and will not be, but you can change [] to array() to fix the issue if you really really want to use PHP <5.3.

**Comment by webscot** [comment]
Thank you very much. We are migrating in the next day or two to a new server. We will try it again then.
